STRIPE_SECRET_KEY: "sk_test_51MYTVySDXEsOpq82PNmfNOOhAHRiEmhqQG0qOuZxv7jd4WND8LP6cvUAL8hWXnJJMs6V3sWuq3tDO1Hymls0UFOV00qb0nYNOW"
STRIPE_PUBLISHABLE_KEY: "pk_test_51MYTVySDXEsOpq82ERbFfILKKF77oRNR4jfPDWn2HHRT31WQbLVMxDKkcHJTnzdfB4mWdywEIaKLNtcnevduPdjj000qJwgeEJ"
